name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Compile
      run: gcc "Advanced Calculator Menu.c" -o calculator -lm

    - name: Build successful
      run: echo "Advanced C Calculator compiled successfully!"
